In [2]:
# 对于三角形ABC，已知R_AB,R_BC,A_ABC,得到相应的笛卡尔坐标
import numpy as np
def jacobian_to_cartesian_three_atom_modified(r12, r23, theta):
    """
    Convert three-atom Jacobian coordinates to Cartesian coordinates with atom 1 as the origin 
    and atom 2 as the point on the axis.
    
    Parameters:
        r12 (float): Bond length between atom 1 and atom 2.
        r23 (float): Bond length between atom 2 and atom 3.
        theta (float): Bond angle between atoms 1-2-3 in radians.
    
    Returns:
        numpy.ndarray: Cartesian coordinates of atoms 1, 2, and 3 in a (3, 3) array.
    """
    # Define the Cartesian coordinates of atom 1 as the origin
    atom1_coords = np.array([0, 0, 0])
    
    # Calculate the x, y, z coordinates of atom 2 relative to atom 1
    atom2_x = r12
    atom2_y = 0
    atom2_coords = np.array([atom2_x, atom2_y, 0])
    
    # Calculate the x, y, z coordinates of atom 3 relative to atom 2
    atom3_x = r23 * np.cos(theta)
    atom3_y = r23 * np.sin(theta)
    atom3_coords = np.array([atom2_x + atom3_x, atom3_y, 0])
    
    # Translate the coordinates of atoms 2 and 3 relative to atom 1
    atom2_coords += atom1_coords
    atom3_coords += atom1_coords
    
    # Combine the coordinates of atoms 1, 2, and 3 into a (3, 3) array
    cartesian_coords = np.vstack((atom1_coords, atom2_coords, atom3_coords))
    print()
    return cartesian_coords

# Test the modified function
jacobian_coords_modified = jacobian_to_cartesian_three_atom_modified(1.0, 1.0, np.pi / 2)
jacobian_coords_modified


array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [7]:
import numpy as np

def jacobi_to_cartesian(r_AB, r_C, theta):
    """
    Convert three-atom Jacobi coordinates to Cartesian coordinates.

    Parameters:
        r_AB (float): Distance between atoms A and B.
        r_C (float): Distance between the center of mass of AB and atom C.
        theta (float): Angle between AB and C in radians.

    Returns:
        numpy.ndarray: Cartesian coordinates of atoms A, B, and C.
    """
    # Define positions of atoms A and B in Jacobi coordinates
    x_A, y_A, z_A = 0, 0, 0
    x_B, y_B, z_B = r_AB, 0, 0
    
    # Calculate the position of the center of mass of AB
    x_AB_cm = (x_A + x_B) / 2
    y_AB_cm = (y_A + y_B) / 2
    z_AB_cm = (z_A + z_B) / 2
    
    # Calculate the position of atom C in the plane of AB
    x_C = x_AB_cm + r_C * np.cos(theta)
    y_C = y_AB_cm + r_C * np.sin(theta)
    z_C = z_AB_cm
    
    return np.array([[x_A, y_A, z_A],
                     [x_B, y_B, z_B],
                     [x_C, y_C, z_C]])

# Example usage:
r_AB = 2.0
r_C = 1.0
theta = np.pi / 2  
cartesian_coords = jacobi_to_cartesian(r_AB, r_C, theta)
print("Cartesian coordinates:")
print(cartesian_coords)


Cartesian coordinates:
[[0. 0. 0.]
 [2. 0. 0.]
 [1. 1. 0.]]


In [14]:
import numpy as np

def convert_jacobi_params(r_AB, r_C, theta):
    """
    Convert three-atom Jacobi coordinates to equivalent Jacobi coordinates.

    Parameters:
        r_AB (float): Distance between atoms A and B.
        r_C (float): Distance between the center of mass of AB and atom C.
        theta (float): Angle between AB and C in radians.

    Returns:
        float: Equivalent bond length (r_1 or r_2).
        float: Equivalent bond length (r_1 or r_2).
        float: Equivalent bond angle (theta).
    """
    # Calculate equivalent bond lengths and angle based on geometric relationships
    r_1 = r_AB + r_C * np.cos(theta)
    r_2 = np.abs(r_AB - r_C * np.cos(theta))
    theta_new = np.arccos((r_AB**2 + r_C**2 - r_1**2) / (2 * r_AB * r_C))
    
    return r_1, r_2, theta_new

# Example usage:
r_AB = 2.0
r_C = 1.0
theta = np.pi / 2  
r_1, r_2, theta_new = convert_jacobi_params(r_AB, r_C, theta)
print("Equivalent Jacobi parameters:")
print(f"r_1: {r_1}, r_2: {r_2}, theta: {theta_new}")


Equivalent Jacobi parameters:
r_1: 2.0, r_2: 2.0, theta: 1.318116071652818
